### ISSUE TITLE
Found a typo on your whitepaper

### ISSUE THREAD

**Issue by nop33** [nuls-io/website#1]
Hi guys!
I was reading your whitepaper and I noticed a small typo, thought I'd let you know.
Keep up the good work!

https://nuls.io/pdf/NulsWhitepaper1.1.pdf
![image](https://user-images.githubusercontent.com/1579899/41498430-ce6c2da6-716d-11e8-854d-5266d8dbf5a5.png)

**Comment by nuls-io** [comment]
Thx, we will fix it.
